 default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform

 stages:
  - test
  - apply
  - destroy

 jb-tf-test:
  stage: test
  script:
    - echo "execute la validation des fichieres Terraform"
    - terraform test --out test
  artifacts:
    paths:
      - test


 jb-tf-apply:
  stage: apply
  script:
    - echo "deployer l'infra et stock les fichier terraform dans un artefact"
    - terraform apply --auto-approve plan
    - terraform state list
  when: always
  allow_failure: false
  artifacts:
    paths:
      - terraform.tfstate


 jb-tf-destroy:
  stage: destroy
  script:
    - echo "supprime l'infrastructure"
    - terraform destroy --auto-approve
  when: manual
  only:
    refs:
      - develop