 default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform

 stages:
  - destroy

 jb-tf-destroy:
  stage: destroy
  variables:
    AWS_ACCESS_KEY_ID: AKIA2G2XJY5PRHXUEGWX
    AWS_SECRET_ACCESS_KEY: 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
  
  script:
    - echo "supprime l'infrastructure"
    - terraform init
    - terraform destroy -var="group_id=test" -auto-approve .